apiVersion: v1
kind: Service
metadata:
  name: php-web-service
  namespace: php-web-service-namespace
spec:
  type: LoadBalancer
  selector:
    app: php-web-service
  ports:
    - port: 80
      targetPort: 80
