#!/bin/bash

echo "Checking for Python 3 installation..."

# Check if Python 3 is already installed
if command -v python3 &>/dev/null; then
  echo "Python 3 is already installed."
  python3 --version
else
  echo "Installing Python 3..."
  yum update -y
  yum install -y python3 python3-pip
  python3 --version
  pip3 --version
fi

# Install Python requirements if they exist
if [ -f "/home/ec2-user/scripts/requirements.txt" ]; then
  echo "Installing Python requirements..."
  pip3 install -r /home/ec2-user/scripts/requirements.txt
fi

echo "Python 3 setup completed."